return {
	Boolean = { fg="#dca3a3", },
	Character = { fg="#dca3a3", bold=true, },
	ColorColumn = { bg="#484848", },
	Comment = { fg="#7f9f7f", },
	Conditional = { fg="#f0dfaf", bold=true, },
	Constant = { fg="#dca3a3", bold=true, },
	Cursor = { fg="#000d18", bg="#8faf9f", bold=true, },
	CursorColumn = { bg="#4f4f4f", },
	CursorLine = { bg="#434443", },
	CursorLineNr = { fg="#d2d39b", bg="#2f2f2f" },
	Debug = { fg="#bca3a3", bold=true, },
	Define = { fg="#ffcfaf", bold=true, },
	Delimiter = { fg="#ffff87", },
	DiffAdd = { bg="#3a3a3a", bold=true, },
	DiffChange = { bg="#333333", },
	DiffDelete = { fg="#333333", bg="#464646", },
	DiffText = { fg="#ecbcbc", bg="#41363c", bold=true, },
	Directory = { fg="#dcdccc", bold=true, },
	ErrorMsg = { fg="#80d4aa", bg="#2f2f2f", bold=true, },
	Exception = { fg="#c3bf9f", bold=true, },
	Float = { fg="#c0bed1", },
	FoldColumn = { fg="#93b3a3", bg="#3f4040", },
	Folded = { fg="#93b3a3", bg="#3f4040", },
	Function = { fg="#ffffaf", bold=true, },
	Identifier = { fg="#d7d7d7", },
	Include = { fg="#dfaf8f" ,bold=true, },
	IncSearch = { bg="#f8f893", fg="#385f38", },
	Keyword = { fg="#ffd7af", bold=true, },
	Label = { fg="#dfcfaf", underline=true, },
	LineNr = { fg="#a8a8a8", bg="#444444" },
	LspInlayHint = { fg="#ffcfaf", },
	Macro = { fg="#ffcfaf", bold=true, },
	MatchParen = { bg="#353535", bold=true, },
	ModeMsg = { fg="#ffcfaf", },
	MoreMsg = { fg="#ffffff", bold=true, },
	NonText = { fg="#464646", },
	Normal = { fg="#d7d7d7", },
	NormalFloat = { bg="#353535", fg="#9f9f9f", },
	Number = { fg="#8cd0d3", },
	Operator = { fg="#f0efd0", },
	PmenuSel = { bg="#242424", fg="#ffffaf", bold=true, },
	PmenuThumb = { bg="#a0afa0", fg="#040404", },
	Pmenu = { bg="#2c2e2e", },
	PmenuSbar = { bg="#2e3330", fg="#000000", },
	PreCondit = { fg="#dfaf8f", bold=true, },
	PreProc = { fg="#ffcfaf", bold=true, },
	Question = { fg="#ffffff", bold=true, },
	Repeat = { fg="#ffd7a7", bold=true, },
	Search = { fg="#ffffe0", bg="#284f28", },
	SignColumn = { fg="#3f3f3f", bold=true, },
	Special = { fg="#ffffaf", bold=true, },
	SpecialChar = { fg="#dca3a3", bold=true, },
	SpecialComment = { fg="#82a282", bold=true, },
	SpecialKey = { fg="#6c6c6c", bold=true, },
	Whitespace = { fg="#6c6c6c", bold=true, },
	SpellBad = { sp="#bc6c4c", fg="#dc8c6c", },
	SpellCap = { sp="#6c6c9c", fg="#8c8cbc", },
	SpellLocal = { sp="#7cac7c", fg="#9ccc9c", },
	SpellRare = { sp="#bc6c9c", fg="#bc8cbc", },
	Statement = { fg="#ffffff", },
	StatusLine = { fg="#dcdccc", },
	StatusLineNC = { fg="#2e3330", bg="#88b090", },
	StorageClass = { fg="#c3bf9f", bold=true, },
	String = { fg="#9e9e9e", },
	Structure = { fg="#efefaf", bold=true, },
	TabLine = { fg="#b6bf98", bg="#353535", bold=true, },
	TabLineFill = { fg="#cfcfaf", bg="#353535", bold=true, },
	TabLineSel = { fg="#efefef", bg="#3a3a39", bold=true, },
	Tag = { fg="#e89393", bold=true, },
	Title = { fg="#ffd7af", bold=true, },
	Todo = { fg="#dfdfdf", bold=true, },
	Type = { fg="#dfdfbf", },
	Typedef = { fg="#dfe4cf", bold=true, },
	Underlined = { fg="#dcdccc", underline=true, },
	VertSplit = { fg="#dfaf8f", bg="#3f3f3f", },
	Visual = { fg="#242424", bg="#a0afa0", },
	VisualNOS = { fg="#242424", bg="#a0afa0", },
	WarningMsg = { fg="#ffffff", bg="#333333", bold=true, },
	WildMenu = { bg="#2c302d", fg="#cbecd0", underline=true, },
	WinSeparator = { fg="#dfaf8f", },
}
